version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "3002:3002"
    networks:
      - microservices-network

networks:
  microservices-network:
